" Neovim config

set nocompatible              " be iMproved, required
filetype off                  " required

let plug_install = 0
let autoload_plug_path = stdpath('config') . '/autoload/plug.vim'
if !filereadable(autoload_plug_path)
    silent exe '!curl -fL --create-dirs -o ' . autoload_plug_path . 
        \ ' https://raw.github.com/junegunn/vim-plug/master/plug.vim'
    execute 'source ' . fnameescape(autoload_plug_path)
    let plug_install = 1
endif
unlet autoload_plug_path

call plug#begin('~/.config/nvim/plugins')

" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plug 'rstacruz/sparkup', {'rtp': 'vim/'}

Plug 'tpope/vim-sensible'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'benekastah/neomake'
Plug 'janko-m/vim-test'
Plug 'kien/ctrlp.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'scrooloose/nerdtree'
Plug 'hashivim/vim-terraform'
Plug 'pearofducks/ansible-vim'
Plug 'vimwiki/vimwiki'
Plug 'tomasr/molokai'

call plug#end()              " required
filetype plugin indent on    " required

" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PlugList          - list configured plugins
" :PlugInstall(!)    - install (update) plugins
" :PlugSearch(!) foo - search (or refresh cache first) for foo
" :PlugClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Begin Normal vimrc
filetype on
filetype off
syntax on
filetype plugin indent on

set modelines=0

set tabstop=4 shiftwidth=4 softtabstop=4 expandtab

set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
set autoread

let mapleader=','

nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=80,109

nnoremap j gj
nnoremap k gk

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

nnoremap ; :

inoremap jj <ESC>

" Disable pylint checking every save
let g:pymode_lint_write = 0

set statusline+=%F
set statusline+=%#warningmsg#
set statusline+=%*

let g:syntastic_mode = "passive"
let g:syntastic_auto_loc_list = 2
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_python_checkers=['flake8']
let g:syntastic_python_flake8_args='--max-line-length=100'
" Syntax highlighting speedup
let g:syntastic_enable_highlighting = 0

" Set key 'R' for run python code
let g:pymode_run_key = 'R'

" Load show documentation plugin
let g:pymode_doc = 1

" Key for show python documentation
let g:pymode_doc_key = 'K'

" Disable python folding
let g:pymode_folding = 0
let g:pep8_map='<leader>8'

" #Autocomplete
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"

" Auto-trim whitespace.
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

autocmd FileType * autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

" Enable menu and pydoc preview
set completeopt=menuone,longest,preview


" Show linenumbers.
set number

" Tweaks for CtrlP Plugin
let g:ctrlp_custom_ignore = 'DS_Store\|^build\|^dist\|git\|.*\.pyc\|\.+pyc\|node_modules\|bower_components\|tmp'

map <C-n> :NERDTreeToggle<CR>


" Remap window nav keys
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:vim_markdown_folding_disabled=1

" Automatically reformat markdown files to 80 characters
au BufRead,BufNewFile *.md setlocal textwidth=80

" Pytest
" nmap <silent><Leader>f <Esc>:w\|:Pytest file verbose<CR>
" nmap <silent><Leader>c <Esc>:w\|:Pytest class verbose<CR>
" nmap <silent><Leader>m <Esc>:w\|:Pytest method verbose<CR>

" Neomake (linter)
autocmd! BufWritePost * Neomake

"nmap <silent> <leader>t :TestNearest<CR>
nmap <silent> <leader>m :w\|:TestNearest<CR>
nmap <silent> <leader>f :w\|:TestFile<CR>
nmap <silent> <leader>a :w\|:TestSuite<CR>
nmap <silent> <leader>l :w\|:TestLast<CR>
nmap <silent> <leader>g :w\|:TestVisit<CR>
let test#strategy = 'neovim'
let test#python#runner = 'pytest'

set background=dark
let g:rehash256 = 1
let g:molokai_original = 1
colorscheme molokai

" Autocomplete
let g:deoplete#enable_at_startup = 1

set mouse-=a
