#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export ZSH=/Users/kevinlondon/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git)

source $ZSH/oh-my-zsh.sh

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel

export PATH="/usr/local/bin:$PATH"
alias vim=nvim
export EDITOR='nvim'
export NVM_DIR=~/.nvm

# Customize to your needs...
# Start SSH Agent
eval `ssh-agent -s`

export ANDROID_HOME=/usr/local/opt/android-sdk

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

echo 'eval "$(pyenv init --path)"' >> ~/.zprofile
echo 'eval "$(pyenv init -)"' >> ~/.zshrc

ssh-add -A
eval "$(pyenv init -)"
